### PR TITLE
add ocaml-version and node-version

### PR DESCRIPTION
**Pull request by kxc-wraikny**
> [haochenx](https://github.com/haochenx) commented [5 days ago](https://github.com/kxcdev/kxc-melange-react-native-template/pull/3#issuecomment-1823155034) • 
> > We also need to update the available-docker-images.json at https://github.com/kxcdev/ocaml-general-gha?
> 
> ah, that sounds necessary. pls do it 🙏

@haochenx 
Should `default: 5.0.0` in action.yml also be updated to 5.1.0?

### CODE REVIEW

**Comment by haochenx** [comment]
>Should default: 5.0.0 in action.yml also be updated to 5.1.0?

let's wait for a while before doing that.

**Review by haochenx — APPROVED** [review]
LGTM!

**Review by haochenx — CHANGES_REQUESTED** [review]
What we'd really like to do is to merge onto the v3 branch (instead of main).

I have changed the base branch and could you please resolve the conflicts? @kxc-wraikny

**Comment by kxc-wraikny** [comment]
@haochenx I have fixed the conflicts.

**Review by haochenx — APPROVED** [review]
LGTM. Let's merge!

**Pull request merged**
